// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

// Package sigwise is the SigWise API client.
//
//	client := sigwise.New("your_key_id", "your_secret")
//	obj, err := client.Objects.Get(ctx, "user-42")
//
// Every request is signed with the API key's secret: the client sends the
// key ID and a short-lived HS256 token bound to the request's method and path.
// The secret itself is never sent.
package sigwise

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	mathrand "math/rand"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"
)

const (
	// Version is the SDK's version.
	Version = "1.0.0"
	// DefaultBaseURL is the API the client talks to unless told otherwise.
	DefaultBaseURL = "https://api.sigwise.ai"

	// tokenTTL is how long each request token is valid (the API allows 5m).
	tokenTTL = 60 * time.Second
)

// Client is the SigWise API client. Create one with New and reuse it; it is
// safe for concurrent use.
type Client struct {
	apiKey     string
	secret     string
	baseURL    string
	httpClient *http.Client
	maxRetries int
	userAgent  string
	header     http.Header

	// The authenticated principal and tenant settings.
	Me *MeService
	// An object is anything you want answers about: a user, a listing, an order.
	Overview *OverviewService
	// An object is anything you want answers about: a user, a listing, an order.
	Objects *ObjectsService
	// Events and messages are the evidence an object's answers are computed from.
	Events *EventsService
	// A signal is a question you ask about every object, such as "is this a scammer?" (`noul`), "how trustworthy is this user?" (`score`) or "what is their buyer intent?" (`choice`).
	Signals *SignalsService
	// The authenticated principal and tenant settings.
	Settings *SettingsService
	// Webhook endpoints receive a signed `POST` for the event types they subscribe to: `analysis.completed` each time an analysis completes, and `rule.triggered` when a rule with a webhook action fires.
	Webhooks *WebhooksService
	// Webhook endpoints receive a signed `POST` for the event types they subscribe to: `analysis.completed` each time an analysis completes, and `rule.triggered` when a rule with a webhook action fires.
	WebhookDeliveries *WebhookDeliveriesService
	// A rule fires an action (email, Slack or webhook) when an object's signal values cross a line you care about, such as `is_scammer >= 90`.
	Rules *RulesService
	// A rule fires an action (email, Slack or webhook) when an object's signal values cross a line you care about, such as `is_scammer >= 90`.
	RuleFirings *RuleFiringsService
	// Create, rotate and revoke the keys your integrations sign requests with.
	APIKeys *APIKeysService
	// Prepaid balance, the billing ledger, and card top-ups.
	Billing *BillingService
	// Analysis volume, spend and token usage over a date range.
	Usage *UsageService
}

// Option configures a Client.
type Option func(*Client)

// WithBaseURL points the client at another deployment, e.g. http://localhost:8080.
func WithBaseURL(u string) Option { return func(c *Client) { c.baseURL = strings.TrimRight(u, "/") } }

// WithHTTPClient sets the HTTP client, e.g. to change the timeout (30s by default).
func WithHTTPClient(h *http.Client) Option { return func(c *Client) { c.httpClient = h } }

// WithMaxRetries sets how many times idempotent requests are retried after a
// network error, a 429 or a 5xx (2 by default).
func WithMaxRetries(n int) Option { return func(c *Client) { c.maxRetries = n } }

// WithHeader adds a header to every request.
func WithHeader(key, value string) Option { return func(c *Client) { c.header.Add(key, value) } }

// New returns a client for the API key and its signing secret.
// Empty values fall back to the ANALYZE_API_KEY and ANALYZE_SECRET environment
// variables, and the base URL to ANALYZE_BASE_URL.
func New(apiKey, secret string, opts ...Option) *Client {
	if apiKey == "" {
		apiKey = os.Getenv("ANALYZE_API_KEY")
	}
	if secret == "" {
		secret = os.Getenv("ANALYZE_SECRET")
	}
	base := os.Getenv("ANALYZE_BASE_URL")
	if base == "" {
		base = DefaultBaseURL
	}
	c := &Client{
		apiKey:     apiKey,
		secret:     secret,
		baseURL:    strings.TrimRight(base, "/"),
		httpClient: &http.Client{Timeout: 30 * time.Second},
		maxRetries: 2,
		userAgent:  "sigwise-go/" + Version + " (go)",
		header:     http.Header{},
	}
	for _, opt := range opts {
		opt(c)
	}
	c.Me = &MeService{c: c}
	c.Overview = &OverviewService{c: c}
	c.Objects = &ObjectsService{c: c}
	c.Events = &EventsService{c: c}
	c.Signals = &SignalsService{c: c}
	c.Settings = &SettingsService{c: c}
	c.Webhooks = &WebhooksService{c: c}
	c.WebhookDeliveries = &WebhookDeliveriesService{c: c}
	c.Rules = &RulesService{c: c}
	c.RuleFirings = &RuleFiringsService{c: c}
	c.APIKeys = &APIKeysService{c: c}
	c.Billing = &BillingService{c: c}
	c.Usage = &UsageService{c: c}
	return c
}

// Error is an error response from the API.
type Error struct {
	// StatusCode is the HTTP status.
	StatusCode int
	// Code is the machine-readable error code, e.g. "not_found".
	Code    string
	Message string
	// Body is the raw response body.
	Body   []byte
	Header http.Header
}

func (e *Error) Error() string {
	return fmt.Sprintf("sigwise: %d %s: %s", e.StatusCode, e.Code, e.Message)
}

// ConnectionError means the request never got a response: a network error,
// a timeout or a cancelled context.
type ConnectionError struct {
	Method, Path string
	Err          error
}

func (e *ConnectionError) Error() string {
	return fmt.Sprintf("sigwise: %s %s: %v", e.Method, e.Path, e.Err)
}

func (e *ConnectionError) Unwrap() error { return e.Err }

// IsStatus reports whether err is an API error with the given HTTP status.
func IsStatus(err error, status int) bool {
	var apiErr *Error
	return errors.As(err, &apiErr) && apiErr.StatusCode == status
}

// SignRequestToken signs the HS256 JWT that authenticates one request: kid
// names the key, iat/exp bound its lifetime, and htm/htu bind it to the
// method and path so it can't be replayed against another endpoint.
func SignRequestToken(apiKey, secret, method, path string, now time.Time) (string, error) {
	header, err := json.Marshal(map[string]string{"alg": "HS256", "typ": "JWT", "kid": apiKey})
	if err != nil {
		return "", err
	}
	jti := make([]byte, 16)
	if _, err := rand.Read(jti); err != nil {
		return "", err
	}
	claims := map[string]any{
		"iat": now.Unix(),
		"exp": now.Add(tokenTTL).Unix(),
		"jti": hex.EncodeToString(jti),
		"htm": strings.ToUpper(method),
	}
	// The server compares htu with the decoded path, so only bind paths it can
	// read back unchanged.
	if !strings.ContainsAny(path, "?#") {
		claims["htu"] = path
	}
	payload, err := json.Marshal(claims)
	if err != nil {
		return "", err
	}
	enc := base64.RawURLEncoding
	signing := enc.EncodeToString(header) + "." + enc.EncodeToString(payload)
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write([]byte(signing))
	return signing + "." + enc.EncodeToString(mac.Sum(nil)), nil
}

var retryStatuses = map[int]bool{408: true, 429: true, 500: true, 502: true, 503: true, 504: true}

func idempotent(method string) bool {
	switch method {
	case http.MethodGet, http.MethodHead, http.MethodPut, http.MethodDelete, http.MethodOptions:
		return true
	}
	return false
}

// do sends a request and decodes a JSON response into out (when non-nil).
func (c *Client) do(ctx context.Context, method, path string, pathParams map[string]string, query url.Values, body, out any) error {
	_, raw, err := c.doRaw(ctx, method, path, pathParams, query, body)
	if err != nil || out == nil || len(raw) == 0 {
		return err
	}
	if err := json.Unmarshal(raw, out); err != nil {
		return fmt.Errorf("sigwise: decode %s %s response: %w", method, path, err)
	}
	return nil
}

// doRaw sends a request and returns the status and body of a 2xx response.
func (c *Client) doRaw(ctx context.Context, method, path string, pathParams map[string]string, query url.Values, body any) (int, []byte, error) {
	if c.apiKey == "" || c.secret == "" {
		return 0, nil, errors.New("sigwise: an API key and its secret are required (pass them to New or set ANALYZE_API_KEY and ANALYZE_SECRET)")
	}
	rawPath, encodedPath := path, path
	for name, value := range pathParams {
		if value == "" {
			return 0, nil, fmt.Errorf("sigwise: %s is required", name)
		}
		rawPath = strings.ReplaceAll(rawPath, "{"+name+"}", value)
		encodedPath = strings.ReplaceAll(encodedPath, "{"+name+"}", url.PathEscape(value))
	}
	q := url.Values{}
	for k, vs := range query {
		q[k] = vs
	}
	q.Set("api_key", c.apiKey)
	target := c.baseURL + encodedPath + "?" + q.Encode()

	var payload []byte
	if body != nil {
		var err error
		if payload, err = json.Marshal(body); err != nil {
			return 0, nil, fmt.Errorf("sigwise: encode request: %w", err)
		}
	}

	retries := 0
	if idempotent(method) {
		retries = c.maxRetries
	}
	for attempt := 0; ; attempt++ {
		status, raw, header, err := c.send(ctx, method, rawPath, target, payload)
		if err != nil {
			if ctx.Err() != nil || attempt >= retries {
				return 0, nil, &ConnectionError{Method: method, Path: rawPath, Err: err}
			}
			if err := sleep(ctx, backoff(attempt, "")); err != nil {
				return 0, nil, &ConnectionError{Method: method, Path: rawPath, Err: err}
			}
			continue
		}
		if status >= 200 && status < 300 {
			return status, raw, nil
		}
		if attempt < retries && retryStatuses[status] {
			if err := sleep(ctx, backoff(attempt, header.Get("Retry-After"))); err != nil {
				return 0, nil, &ConnectionError{Method: method, Path: rawPath, Err: err}
			}
			continue
		}
		apiErr := &Error{StatusCode: status, Code: "http_" + strconv.Itoa(status), Body: raw, Header: header,
			Message: fmt.Sprintf("%s %s returned %d", method, rawPath, status)}
		var envelope struct {
			Error struct {
				Code    string `json:"code"`
				Message string `json:"message"`
			} `json:"error"`
		}
		if json.Unmarshal(raw, &envelope) == nil && envelope.Error.Code != "" {
			apiErr.Code, apiErr.Message = envelope.Error.Code, envelope.Error.Message
		}
		return status, raw, apiErr
	}
}

func (c *Client) send(ctx context.Context, method, rawPath, target string, payload []byte) (int, []byte, http.Header, error) {
	var reader io.Reader
	if payload != nil {
		reader = bytes.NewReader(payload)
	}
	req, err := http.NewRequestWithContext(ctx, method, target, reader)
	if err != nil {
		return 0, nil, nil, err
	}
	token, err := SignRequestToken(c.apiKey, c.secret, method, rawPath, time.Now())
	if err != nil {
		return 0, nil, nil, err
	}
	for k, vs := range c.header {
		req.Header[k] = vs
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", c.userAgent)
	req.Header.Set("Authorization", "Bearer "+token)
	if payload != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	resp, err := c.httpClient.Do(req)
	if err != nil {
		return 0, nil, nil, err
	}
	defer resp.Body.Close()
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return 0, nil, nil, err
	}
	return resp.StatusCode, raw, resp.Header, nil
}

func backoff(attempt int, retryAfter string) time.Duration {
	if s, err := strconv.ParseFloat(retryAfter, 64); err == nil && s >= 0 {
		return time.Duration(math.Min(s, 60) * float64(time.Second))
	}
	base := math.Min(500*math.Pow(2, float64(attempt)), 8000)
	return time.Duration(base/2+mathrand.Float64()*base/2) * time.Millisecond
}

func sleep(ctx context.Context, d time.Duration) error {
	t := time.NewTimer(d)
	defer t.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-t.C:
		return nil
	}
}

// String returns a pointer to v, for optional request fields.
func String(v string) *string { return &v }

// Bool returns a pointer to v, for optional request fields.
func Bool(v bool) *bool { return &v }

// Int returns a pointer to v, for optional request fields.
func Int(v int) *int { return &v }

// Float64 returns a pointer to v, for optional request fields.
func Float64(v float64) *float64 { return &v }
