// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

package sigwise

import "time"

// time is referenced by date-time fields.
var _ time.Time

// APIKey is part of the SigWise API.
type APIKey struct {
	ID string `json:"id"`
	// The public key ID, sent as `api_key`.
	Key    string       `json:"key"`
	Name   string       `json:"name"`
	Status APIKeyStatus `json:"status"`
	// Whether the key can sign requests. Legacy keys can't until rotated.
	HasSecret bool `json:"has_secret"`
	// Created before request signing; rotate it to get a signing secret.
	Legacy        *bool      `json:"legacy,omitempty"`
	LegacyPreview *string    `json:"legacy_preview,omitempty"`
	CreatedAt     time.Time  `json:"created_at"`
	LastUsedAt    *time.Time `json:"last_used_at,omitempty"`
	LegacyUsedAt  *time.Time `json:"legacy_used_at,omitempty"`
}

// APIKeyCreate is part of the SigWise API.
type APIKeyCreate struct {
	Name *string `json:"name,omitempty"`
}

// APIKeyList is part of the SigWise API.
type APIKeyList struct {
	APIKeys []APIKey `json:"api_keys"`
}

// APIKeySecret is part of the SigWise API.
type APIKeySecret struct {
	APIKey APIKey `json:"api_key"`
	// The public key ID.
	Key string `json:"key"`
	// The signing secret. Shown only once.
	Secret string `json:"secret"`
	Note   string `json:"note"`
}

// APIKeyStatus is part of the SigWise API.
type APIKeyStatus string

// Values of APIKeyStatus.
const (
	APIKeyStatusActive   APIKeyStatus = "active"
	APIKeyStatusInactive APIKeyStatus = "inactive"
	APIKeyStatusRevoked  APIKeyStatus = "revoked"
)

// APIKeyUpdate is part of the SigWise API.
type APIKeyUpdate struct {
	Name   *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

// Depends on `action_type`:
//
// - `email`: `{"to": "abuse@acme.com", "subject": "…"}` (`subject` optional)
// - `slack`: `{"webhook_url": "https://hooks.slack.com/…"}`
// - `webhook`: `{"endpoint_id": "<registered endpoint id>"}`
type ActionConfig map[string]any

// ActionType is part of the SigWise API.
type ActionType string

// Values of ActionType.
const (
	ActionTypeEmail   ActionType = "email"
	ActionTypeSlack   ActionType = "slack"
	ActionTypeWebhook ActionType = "webhook"
)

// AnalysisCompletedEvent is part of the SigWise API.
type AnalysisCompletedEvent struct {
	Event      string    `json:"event"`
	ObjectID   string    `json:"object_id"`
	TenantID   string    `json:"tenant_id"`
	Model      string    `json:"model"`
	OccurredAt time.Time `json:"occurred_at"`
	Answers    []Answer  `json:"answers"`
}

// AnalyzeAllScheduled is part of the SigWise API.
type AnalyzeAllScheduled struct {
	// How many objects were scheduled.
	Scheduled      int    `json:"scheduled"`
	AnalysisStatus string `json:"analysis_status"`
}

// AnalyzeScheduled is part of the SigWise API.
type AnalyzeScheduled struct {
	ObjectID       string `json:"object_id"`
	AnalysisStatus string `json:"analysis_status"`
}

// One signal's answer. Only the fields for its `type` are set.
type Answer struct {
	Signal string `json:"signal"`
	// `noul`: yes/no probability.
	Type SignalType `json:"type"`
	// `noul`: the probability the answer is yes.
	Noul *float64 `json:"noul,omitempty"`
	// `choice`: the most likely option.
	Choice *string `json:"choice,omitempty"`
	// `score`: the position on the spectrum, from 0 (the first level) to the
	// number of levels minus one.
	Score *float64 `json:"score,omitempty"`
	// `choice` and `score`: the probability of each option or level.
	Probabilities map[string]float64 `json:"probabilities,omitempty"`
	// `choice` and `score`: the analyzer's confidence.
	Confidence *float64 `json:"confidence,omitempty"`
}

// BackfillEstimate is part of the SigWise API.
type BackfillEstimate struct {
	// Objects with no answer for the signal.
	Objects int `json:"objects"`
	// Estimated cost in micro-dollars (1e-6 USD), an upper bound. 0 without paid
	// history.
	EstimatedCostMicros int `json:"estimated_cost_micros"`
}

// BackfillStatus is part of the SigWise API.
type BackfillStatus struct {
	Estimate BackfillEstimate `json:"estimate"`
	Backfill *SignalBackfill  `json:"backfill"`
}

// Balance is part of the SigWise API.
type Balance struct {
	BalanceCents int    `json:"balance_cents"`
	Currency     string `json:"currency"`
	// Whether analyses are billed on this deployment.
	MeteringEnabled bool `json:"metering_enabled"`
	// `block` pauses analyses at an empty balance; `grace` lets it go negative.
	Enforcement string `json:"enforcement"`
	// Whether card top-ups are available.
	SelfServeTopup           bool `json:"self_serve_topup"`
	LowBalanceThresholdCents int  `json:"low_balance_threshold_cents"`
	TopupMinCents            *int `json:"topup_min_cents,omitempty"`
	TopupMaxCents            *int `json:"topup_max_cents,omitempty"`
}

// How many objects have one `object_type`.
type CategoryCount struct {
	Name  string `json:"name"`
	Count int    `json:"count"`
}

// CheckoutCreate is part of the SigWise API.
type CheckoutCreate struct {
	// Within the deployment's `topup_min_cents`–`topup_max_cents`.
	AmountCents int `json:"amount_cents"`
}

// CheckoutSession is part of the SigWise API.
type CheckoutSession struct {
	ID string `json:"id"`
	// Send the customer here to pay.
	URL string `json:"url"`
}

// CheckoutStatus is part of the SigWise API.
type CheckoutStatus struct {
	ID                string `json:"id"`
	Status            string `json:"status"`
	AmountCents       *int   `json:"amount_cents,omitempty"`
	BalanceAfterCents *int   `json:"balance_after_cents,omitempty"`
}

// A rolling summary of an object's older events.
type CompactedState struct {
	TotalEvents    int            `json:"total_events"`
	Messages       int            `json:"messages"`
	Actions        int            `json:"actions"`
	ByAction       map[string]int `json:"by_action,omitempty"`
	SampleMessages []string       `json:"sample_messages,omitempty"`
	FirstSeen      time.Time      `json:"first_seen"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

// `dead` deliveries are in the dead-letter queue: permanently rejected, or out
// of retries.
type DeliveryStatus string

// Values of DeliveryStatus.
const (
	DeliveryStatusPending    DeliveryStatus = "pending"
	DeliveryStatusDelivering DeliveryStatus = "delivering"
	DeliveryStatusDelivered  DeliveryStatus = "delivered"
	DeliveryStatusDead       DeliveryStatus = "dead"
)

// Event is part of the SigWise API.
type Event struct {
	// `event` is a discrete action (e.g.
	Type    EventType `json:"type"`
	Name    *string   `json:"name,omitempty"`
	Content *string   `json:"content,omitempty"`
	// Arbitrary structured attributes.
	Metadata   Metadata  `json:"metadata,omitempty"`
	OccurredAt time.Time `json:"occurred_at"`
}

// EventInput is part of the SigWise API.
type EventInput struct {
	// `event` is a discrete action (e.g.
	Type EventType `json:"type"`
	// The event name, or a message's subject.
	Name *string `json:"name,omitempty"`
	// Free text, such as a message body.
	Content *string `json:"content,omitempty"`
	// Arbitrary structured attributes.
	Metadata Metadata `json:"metadata,omitempty"`
	// When it happened. Defaults to the time the API received it.
	OccurredAt *time.Time `json:"occurred_at,omitempty"`
}

// EventList is part of the SigWise API.
type EventList struct {
	Events []Event `json:"events"`
}

// `event` is a discrete action (e.g. `profile.updated`); `message` is
// free-form text.
type EventType string

// Values of EventType.
const (
	EventTypeEvent   EventType = "event"
	EventTypeMessage EventType = "message"
)

// IngestAccepted is part of the SigWise API.
type IngestAccepted struct {
	ObjectID string `json:"object_id"`
	// How many events were recorded.
	Accepted       int    `json:"accepted"`
	AnalysisStatus string `json:"analysis_status"`
	// The debounce window before the analysis runs.
	AnalysisDelayMs int `json:"analysis_delay_ms"`
}

// IngestRequest is part of the SigWise API.
type IngestRequest struct {
	// Optional classification, e.g. `user` or `listing`.
	ObjectType *string      `json:"object_type,omitempty"`
	Events     []EventInput `json:"events"`
	// Score the object inline and return the verdict (`200`) instead of scheduling
	// analysis (`202`).
	Wait *bool `json:"wait,omitempty"`
	// With `wait`, score only these signal keys. Ignored otherwise.
	Signals []string `json:"signals,omitempty"`
	// With `wait`, whether to score over the object's prior history (`true`) or
	// only this request's events (`false`).
	IncludeHistory *bool `json:"include_history,omitempty"`
}

// The totals of a bulk run, on the entry that stands for it with
// `group=batch`.
type LedgerBatch struct {
	// How many charges the run has.
	Count int `json:"count"`
	// The run's total, in micro-dollars (negative).
	DeltaMicros  int `json:"delta_micros"`
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
	// How many distinct models the run was billed for.
	Models int `json:"models"`
	// One of the models; the only one when `models` is 1.
	Model *string `json:"model,omitempty"`
	// When the run's first charge was made.
	FirstAt time.Time `json:"first_at"`
}

// LedgerEntry is part of the SigWise API.
type LedgerEntry struct {
	ID string `json:"id"`
	// Negative for a charge, positive for a credit. Sub-cent charges round to 0;
	// see `delta_micros`.
	DeltaCents        int `json:"delta_cents"`
	BalanceAfterCents int `json:"balance_after_cents"`
	// The exact amount in micro-dollars (1e-6 USD).
	DeltaMicros        int      `json:"delta_micros"`
	BalanceAfterMicros int      `json:"balance_after_micros"`
	Reason             string   `json:"reason"`
	Model              *string  `json:"model,omitempty"`
	ObjectID           *string  `json:"object_id,omitempty"`
	CostUsd            *float64 `json:"cost_usd,omitempty"`
	CostMargin         *float64 `json:"cost_margin,omitempty"`
	InputTokens        *int     `json:"input_tokens,omitempty"`
	OutputTokens       *int     `json:"output_tokens,omitempty"`
	// The Stripe Checkout Session that paid for a top-up.
	PaymentRef *string `json:"payment_ref,omitempty"`
	// Shared by the charges of one bulk run (re-analyzing all objects, or a signal
	// backfill). Absent for a single object's analysis and for credits.
	BatchID *string `json:"batch_id,omitempty"`
	// The totals of a bulk run, on the entry that stands for it with
	// `group=batch`.
	Batch     *LedgerBatch `json:"batch,omitempty"`
	CreatedAt time.Time    `json:"created_at"`
}

// LedgerPage is part of the SigWise API.
type LedgerPage struct {
	Entries []LedgerEntry `json:"entries"`
	// Pass as `cursor` for the next page. Empty on the last page.
	NextCursor string `json:"next_cursor"`
}

// Me is part of the SigWise API.
type Me struct {
	// `tenant` for API keys, `console` for a signed-in user.
	AuthType   string  `json:"auth_type"`
	TenantID   string  `json:"tenant_id"`
	TenantName string  `json:"tenant_name"`
	UserID     *string `json:"user_id,omitempty"`
	Email      *string `json:"email,omitempty"`
	Role       *string `json:"role,omitempty"`
	Onboarded  *bool   `json:"onboarded,omitempty"`
}

// Arbitrary structured attributes.
type Metadata map[string]any

// ModerationVerdict is part of the SigWise API.
type ModerationVerdict struct {
	ObjectID string `json:"object_id"`
	// How many events were recorded.
	Accepted int `json:"accepted"`
	// False when no configured signal matched, so nothing was scored.
	Analyzed        bool `json:"analyzed"`
	HistoryIncluded bool `json:"history_included"`
	// The model that produced the answers, e.g. `model-1`.
	Model     string   `json:"model"`
	LatencyMs int      `json:"latency_ms"`
	Answers   []Answer `json:"answers"`
	// Why nothing was analyzed, when `analyzed` is false.
	Reason *string `json:"reason,omitempty"`
}

// ObjectAnalysis is part of the SigWise API.
type ObjectAnalysis struct {
	ObjectID   string         `json:"object_id"`
	EventCount int            `json:"event_count"`
	Analysis   []SignalResult `json:"analysis"`
	// Enabled signals with no answer yet.
	Pending []string `json:"pending"`
}

// ObjectList is part of the SigWise API.
type ObjectList struct {
	Objects []ObjectSummary `json:"objects"`
	Limit   int             `json:"limit"`
	Offset  int             `json:"offset"`
	// Pass as `cursor` to fetch the next page. Absent on the last page and for
	// signal queries.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ObjectState is part of the SigWise API.
type ObjectState struct {
	ObjectID string `json:"object_id"`
	// How many events have been folded into the summary.
	CompactedEvents  int             `json:"compacted_events"`
	CompactedThrough *time.Time      `json:"compacted_through,omitempty"`
	CompactedState   *CompactedState `json:"compacted_state,omitempty"`
	LastAnalyzedAt   *time.Time      `json:"last_analyzed_at,omitempty"`
}

// ObjectSummary is part of the SigWise API.
type ObjectSummary struct {
	ObjectID    string         `json:"object_id"`
	ObjectType  string         `json:"object_type"`
	DisplayName *string        `json:"display_name,omitempty"`
	EventCount  int            `json:"event_count"`
	LastSeen    time.Time      `json:"last_seen"`
	Analysis    []SignalResult `json:"analysis"`
	Pending     []string       `json:"pending"`
}

// Overview is part of the SigWise API.
type Overview struct {
	Objects int `json:"objects"`
	Signals int `json:"signals"`
	// Share of objects with at least one answer, 0–1.
	AnalyzedPct float64 `json:"analyzed_pct"`
	// Events recorded in the last 24 hours.
	EventsToday   int             `json:"events_today"`
	Flagged       int             `json:"flagged"`
	SignalSummary []SignalSummary `json:"signal_summary"`
	Categories    []CategoryCount `json:"categories"`
	TopRisk       []RiskyObject   `json:"top_risk"`
}

// PlaygroundRequest is part of the SigWise API.
type PlaygroundRequest struct {
	// Optional classification, e.g. `user` or `listing`.
	ObjectType *string      `json:"object_type,omitempty"`
	Events     []EventInput `json:"events"`
	// Score only these signal keys. Omit to score every enabled signal.
	Signals []string `json:"signals,omitempty"`
}

// PlaygroundResult is part of the SigWise API.
type PlaygroundResult struct {
	// False when no enabled signal matched, so nothing was scored.
	Analyzed bool `json:"analyzed"`
	// The model that produced the answers, e.g. `model-1`.
	Model     string   `json:"model"`
	LatencyMs int      `json:"latency_ms"`
	Answers   []Answer `json:"answers"`
	// What the run was charged, in millionths of a US dollar.
	CostMicros int `json:"cost_micros"`
	// How many events were scored.
	EventsCount int `json:"events_count"`
	// Why nothing was analyzed, when `analyzed` is false.
	Reason *string `json:"reason,omitempty"`
}

// One of the objects with the highest yes/no probabilities.
type RiskyObject struct {
	ObjectID    string  `json:"object_id"`
	DisplayName *string `json:"display_name,omitempty"`
	Risk        float64 `json:"risk"`
}

// Rule is part of the SigWise API.
type Rule struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// The condition, e.g. `is_scammer >= 90 and trust_score < 1`.
	When       string     `json:"when"`
	ActionType ActionType `json:"action_type"`
	// Depends on `action_type`: - `email`: `{"to": "abuse@acme.com", "subject":
	// "…"}` (`subject` optional) - `slack`: `{"webhook_url":
	// "https://hooks.slack.com/…"}` - `webhook`: `{"endpoint_id": "<registered
	// endpoint id>"}`
	ActionConfig ActionConfig `json:"action_config"`
	Enabled      bool         `json:"enabled"`
	// 0 fires only when the condition turns true; more lets the rule re-fire after
	// that long while it stays true.
	CooldownSeconds int       `json:"cooldown_seconds"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

// RuleCreate is part of the SigWise API.
type RuleCreate struct {
	Name       *string    `json:"name,omitempty"`
	When       string     `json:"when"`
	ActionType ActionType `json:"action_type"`
	// Depends on `action_type`: - `email`: `{"to": "abuse@acme.com", "subject":
	// "…"}` (`subject` optional) - `slack`: `{"webhook_url":
	// "https://hooks.slack.com/…"}` - `webhook`: `{"endpoint_id": "<registered
	// endpoint id>"}`
	ActionConfig    ActionConfig `json:"action_config"`
	Enabled         *bool        `json:"enabled,omitempty"`
	CooldownSeconds *int         `json:"cooldown_seconds,omitempty"`
}

// RuleFiring is part of the SigWise API.
type RuleFiring struct {
	ID          string `json:"id"`
	RuleID      string `json:"rule_id"`
	ObjectID    string `json:"object_id"`
	MatchedWhen string `json:"matched_when"`
	// The signal values that satisfied the condition.
	SignalValues map[string]any `json:"signal_values,omitempty"`
	ActionType   ActionType     `json:"action_type"`
	Status       string         `json:"status"`
	// The error, or a short success note.
	Detail  *string   `json:"detail,omitempty"`
	FiredAt time.Time `json:"fired_at"`
}

// RuleFiringList is part of the SigWise API.
type RuleFiringList struct {
	Firings []RuleFiring `json:"firings"`
}

// RuleList is part of the SigWise API.
type RuleList struct {
	Rules []Rule `json:"rules"`
}

// RuleTriggeredEvent is part of the SigWise API.
type RuleTriggeredEvent struct {
	Event       string    `json:"event"`
	RuleID      string    `json:"rule_id"`
	RuleName    *string   `json:"rule_name,omitempty"`
	TenantID    string    `json:"tenant_id"`
	ObjectID    string    `json:"object_id"`
	MatchedWhen string    `json:"matched_when"`
	Model       *string   `json:"model,omitempty"`
	OccurredAt  time.Time `json:"occurred_at"`
	Values      []Answer  `json:"values"`
}

// RuleUpdate is part of the SigWise API.
type RuleUpdate struct {
	Name       *string     `json:"name,omitempty"`
	When       *string     `json:"when,omitempty"`
	ActionType *ActionType `json:"action_type,omitempty"`
	// Depends on `action_type`: - `email`: `{"to": "abuse@acme.com", "subject":
	// "…"}` (`subject` optional) - `slack`: `{"webhook_url":
	// "https://hooks.slack.com/…"}` - `webhook`: `{"endpoint_id": "<registered
	// endpoint id>"}`
	ActionConfig    ActionConfig `json:"action_config,omitempty"`
	Enabled         *bool        `json:"enabled,omitempty"`
	CooldownSeconds *int         `json:"cooldown_seconds,omitempty"`
}

// Settings is part of the SigWise API.
type Settings struct {
	// Creating a signal automatically backfills existing objects for it. Off by
	// default because each analysis is billed.
	AutoBackfillSignals bool `json:"auto_backfill_signals"`
}

// SettingsUpdate is part of the SigWise API.
type SettingsUpdate struct {
	AutoBackfillSignals *bool `json:"auto_backfill_signals,omitempty"`
}

// Signal is part of the SigWise API.
type Signal struct {
	Key string `json:"key"`
	// `noul`: yes/no probability.
	Type         SignalType `json:"type"`
	Instructions any        `json:"instructions"`
	Criteria     any        `json:"criteria,omitempty"`
	Enabled      bool       `json:"enabled"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	// Set only when creating the signal started a backfill
	// (`auto_backfill_signals`).
	Backfill *SignalBackfill `json:"backfill,omitempty"`
}

// SignalBackfill is part of the SigWise API.
type SignalBackfill struct {
	SignalKey string `json:"signal_key"`
	Status    string `json:"status"`
	// Objects enqueued when the backfill started.
	Total int `json:"total"`
	// Objects answered since it started.
	Completed int `json:"completed"`
	// Objects still queued or running.
	Pending   int       `json:"pending"`
	StartedAt time.Time `json:"started_at"`
}

// SignalInput is part of the SigWise API.
type SignalInput struct {
	// `noul`: yes/no probability.
	Type SignalType `json:"type"`
	// What the analyzer should decide. Usually a string; objects and arrays are
	// passed through verbatim.
	Instructions any `json:"instructions"`
	// Depends on `type`; see the operation description.
	Criteria any   `json:"criteria,omitempty"`
	Enabled  *bool `json:"enabled,omitempty"`
}

// SignalList is part of the SigWise API.
type SignalList struct {
	Signals []Signal `json:"signals"`
}

// The latest answer for one signal. Only the fields for its `type` are set.
type SignalResult struct {
	Key string `json:"key"`
	// `noul`: yes/no probability.
	Type          SignalType         `json:"type"`
	Noul          *float64           `json:"noul,omitempty"`
	Choice        *string            `json:"choice,omitempty"`
	Score         *float64           `json:"score,omitempty"`
	Probabilities map[string]float64 `json:"probabilities,omitempty"`
	Confidence    *float64           `json:"confidence,omitempty"`
	Model         *string            `json:"model,omitempty"`
	ComputedAt    time.Time          `json:"computed_at"`
}

// SignalSummary is part of the SigWise API.
type SignalSummary struct {
	Key string `json:"key"`
	// `noul`: yes/no probability.
	Type SignalType `json:"type"`
	// Objects with an answer for the signal.
	Total int      `json:"total"`
	Avg   *float64 `json:"avg,omitempty"`
	// Objects answered high (yes/no signals).
	High    *int     `json:"high,omitempty"`
	HighPct *float64 `json:"high_pct,omitempty"`
	// `choice` signals: the share of each option.
	Choices map[string]float64 `json:"choices,omitempty"`
}

// `noul`: yes/no probability. `score`: position on a labelled spectrum.
// `choice`: one of N options.
type SignalType string

// Values of SignalType.
const (
	SignalTypeNoul   SignalType = "noul"
	SignalTypeChoice SignalType = "choice"
	SignalTypeScore  SignalType = "score"
)

// Usage is part of the SigWise API.
type Usage struct {
	From            string `json:"from"`
	To              string `json:"to"`
	Currency        string `json:"currency"`
	MeteringEnabled bool   `json:"metering_enabled"`
	BalanceCents    int    `json:"balance_cents"`
	// Average spend per elapsed day of the range, in micro-dollars.
	BurnRateMicrosPerDay int `json:"burn_rate_micros_per_day"`
	// Balance divided by burn rate. Omitted without spend or balance.
	RunwayDays *float64         `json:"runway_days,omitempty"`
	Totals     UsageTotals      `json:"totals"`
	Series     []UsageDay       `json:"series"`
	ByModel    []UsageBreakdown `json:"by_model"`
	BySource   []UsageBreakdown `json:"by_source"`
	BySignal   []UsageSignal    `json:"by_signal"`
}

// UsageBreakdown is part of the SigWise API.
type UsageBreakdown struct {
	Key          string `json:"key"`
	Analyses     int    `json:"analyses"`
	SpendMicros  int    `json:"spend_micros"`
	InputTokens  int    `json:"input_tokens"`
	OutputTokens int    `json:"output_tokens"`
}

// UsageDay is part of the SigWise API.
type UsageDay struct {
	Date        string `json:"date"`
	Analyses    int    `json:"analyses"`
	Async       int    `json:"async"`
	Sync        int    `json:"sync"`
	SpendMicros int    `json:"spend_micros"`
}

// UsageSignal is part of the SigWise API.
type UsageSignal struct {
	Signal   string `json:"signal"`
	Analyses int    `json:"analyses"`
}

// UsageTotals is part of the SigWise API.
type UsageTotals struct {
	Analyses     int `json:"analyses"`
	SpendMicros  int `json:"spend_micros"`
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
}

// WebhookDelivery is part of the SigWise API.
type WebhookDelivery struct {
	ID         string  `json:"id"`
	EndpointID string  `json:"endpoint_id"`
	EventType  string  `json:"event_type"`
	ObjectID   *string `json:"object_id,omitempty"`
	// `dead` deliveries are in the dead-letter queue: permanently rejected, or out
	// of retries.
	Status      DeliveryStatus `json:"status"`
	Attempts    int            `json:"attempts"`
	MaxAttempts int            `json:"max_attempts"`
	// The endpoint's last HTTP status, if it answered.
	LastStatusCode *int    `json:"last_status_code,omitempty"`
	LastError      *string `json:"last_error,omitempty"`
	// When the next attempt is due.
	RunAfter    time.Time  `json:"run_after"`
	DeliveredAt *time.Time `json:"delivered_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	// The body that is (or was) delivered.
	Payload map[string]any `json:"payload,omitempty"`
}

// WebhookDeliveryList is part of the SigWise API.
type WebhookDeliveryList struct {
	Deliveries []WebhookDelivery `json:"deliveries"`
}

// WebhookEndpoint is part of the SigWise API.
type WebhookEndpoint struct {
	ID          string `json:"id"`
	URL         string `json:"url"`
	Description string `json:"description"`
	Enabled     bool   `json:"enabled"`
	// Only deliver analyses that answered one of these signals. Empty means every
	// analysis.
	SignalKeys []string `json:"signal_keys"`
	// The event types this endpoint receives.
	Events    []WebhookEventType `json:"events"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// WebhookEndpointCreate is part of the SigWise API.
type WebhookEndpointCreate struct {
	// An `http` or `https` URL.
	URL         string   `json:"url"`
	Description *string  `json:"description,omitempty"`
	SignalKeys  []string `json:"signal_keys,omitempty"`
	// The event types to deliver. Omit to receive every event type. Use
	// `["rule.triggered"]` for an endpoint that only receives rule firings.
	Events  []WebhookEventType `json:"events,omitempty"`
	Enabled *bool              `json:"enabled,omitempty"`
}

// WebhookEndpointCreated is part of the SigWise API.
type WebhookEndpointCreated struct {
	Endpoint WebhookEndpoint `json:"endpoint"`
	// The signing secret. Shown only once.
	Secret string `json:"secret"`
	Note   string `json:"note"`
}

// WebhookEndpointList is part of the SigWise API.
type WebhookEndpointList struct {
	Webhooks []WebhookEndpoint `json:"webhooks"`
}

// WebhookEndpointUpdate is part of the SigWise API.
type WebhookEndpointUpdate struct {
	URL         *string            `json:"url,omitempty"`
	Description *string            `json:"description,omitempty"`
	SignalKeys  []string           `json:"signal_keys,omitempty"`
	Events      []WebhookEventType `json:"events,omitempty"`
	Enabled     *bool              `json:"enabled,omitempty"`
}

// WebhookEventType is part of the SigWise API.
type WebhookEventType string

// Values of WebhookEventType.
const (
	WebhookEventTypeAnalysisCompleted WebhookEventType = "analysis.completed"
	WebhookEventTypeRuleTriggered     WebhookEventType = "rule.triggered"
)
