// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

package sigwise

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"time"
)

var (
	_ = fmt.Sprint
	_ url.Values
	_ time.Time
)

// ListObjectsParams are the query parameters of ObjectsService.List.
type ListObjectsParams struct {
	// Substring search, or a signal query like `is_scammer >= 90, buyer_intent =
	// ready_to_buy`.
	Q *string
	// `recent` (last seen first, the default), `flagged` (highest yes/no
	// probability first) or `trust` (highest score first).
	Sort  *string
	Limit *int
	// Rows to skip. Prefer `cursor` for deep pages; offsets get slower the further
	// they go.
	Offset *int
	// The `next_cursor` of the previous page. Pages by position rather than
	// offset, so every page is equally fast; `offset` is ignored when set. Keep
	// `q` and `sort` the same across pages. Signal queries page by `offset` only.
	Cursor *string
}

func (p *ListObjectsParams) values() url.Values {
	q := url.Values{}
	if p == nil {
		return q
	}
	if p.Q != nil {
		q.Set("q", *p.Q)
	}
	if p.Sort != nil {
		q.Set("sort", *p.Sort)
	}
	if p.Limit != nil {
		q.Set("limit", fmt.Sprint(*p.Limit))
	}
	if p.Offset != nil {
		q.Set("offset", fmt.Sprint(*p.Offset))
	}
	if p.Cursor != nil {
		q.Set("cursor", *p.Cursor)
	}
	return q
}

// IngestEventsResponse is the response of EventsService.Ingest. The field matching
// StatusCode is set.
type IngestEventsResponse struct {
	StatusCode int
	// ModerationVerdict is set for a 200 response.
	ModerationVerdict *ModerationVerdict
	// IngestAccepted is set for a 202 response.
	IngestAccepted *IngestAccepted
}

// ListWebhookDeliveriesParams are the query parameters of WebhookDeliveriesService.List.
type ListWebhookDeliveriesParams struct {
	Status     *DeliveryStatus
	EndpointID *string
	Limit      *int
}

func (p *ListWebhookDeliveriesParams) values() url.Values {
	q := url.Values{}
	if p == nil {
		return q
	}
	if p.Status != nil {
		q.Set("status", string(*p.Status))
	}
	if p.EndpointID != nil {
		q.Set("endpoint_id", *p.EndpointID)
	}
	if p.Limit != nil {
		q.Set("limit", fmt.Sprint(*p.Limit))
	}
	return q
}

// ListRuleFiringsParams are the query parameters of RuleFiringsService.List.
type ListRuleFiringsParams struct {
	RuleID   *string
	ObjectID *string
	Limit    *int
}

func (p *ListRuleFiringsParams) values() url.Values {
	q := url.Values{}
	if p == nil {
		return q
	}
	if p.RuleID != nil {
		q.Set("rule_id", *p.RuleID)
	}
	if p.ObjectID != nil {
		q.Set("object_id", *p.ObjectID)
	}
	if p.Limit != nil {
		q.Set("limit", fmt.Sprint(*p.Limit))
	}
	return q
}

// ListLedgerParams are the query parameters of BillingService.ListLedger.
type ListLedgerParams struct {
	// Only credits (funds added) or only charges (analyses).
	Type   *string
	Limit  *int
	Cursor *string
}

func (p *ListLedgerParams) values() url.Values {
	q := url.Values{}
	if p == nil {
		return q
	}
	if p.Type != nil {
		q.Set("type", *p.Type)
	}
	if p.Limit != nil {
		q.Set("limit", fmt.Sprint(*p.Limit))
	}
	if p.Cursor != nil {
		q.Set("cursor", *p.Cursor)
	}
	return q
}

// GetUsageParams are the query parameters of UsageService.Get.
type GetUsageParams struct {
	// First day, `YYYY-MM-DD`. Defaults to 29 days before `to`.
	From *string
	// Last day, `YYYY-MM-DD`. Defaults to today.
	To *string
}

func (p *GetUsageParams) values() url.Values {
	q := url.Values{}
	if p == nil {
		return q
	}
	if p.From != nil {
		q.Set("from", *p.From)
	}
	if p.To != nil {
		q.Set("to", *p.To)
	}
	return q
}

// MeService groups the me operations. The authenticated principal and tenant
// settings.
type MeService struct{ c *Client }

// Get — get the current principal.
//
// Returns the tenant the credential belongs to. For console tokens it also
// returns the signed-in user and whether they finished onboarding.
//
// GET /v1/me
func (s *MeService) Get(ctx context.Context) (*Me, error) {
	var out Me
	if err := s.c.do(ctx, "GET", "/v1/me", nil, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// OverviewService groups the overview operations. An object is anything you
// want answers about: a user, a listing, an order.
type OverviewService struct{ c *Client }

// Get — get tenant overview.
//
// Tenant-wide totals and per-signal value distributions, computed with SQL
// aggregates.
//
// GET /v1/overview
func (s *OverviewService) Get(ctx context.Context) (*Overview, error) {
	var out Overview
	if err := s.c.do(ctx, "GET", "/v1/overview", nil, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ObjectsService groups the objects operations. An object is anything you want
// answers about: a user, a listing, an order.
type ObjectsService struct{ c *Client }

// AnalyzeAll — re-analyze every object.
//
// Schedules a re-analysis of every object the tenant has, typically after
// changing signal configuration. Jobs run at bulk priority, behind live
// traffic. Each analysis is billed.
//
// POST /v1/analyze
func (s *ObjectsService) AnalyzeAll(ctx context.Context) (*AnalyzeAllScheduled, error) {
	var out AnalyzeAllScheduled
	if err := s.c.do(ctx, "POST", "/v1/analyze", nil, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List — list objects.
//
// Returns one page of objects with their latest analysis.
//
// `q` is either a substring of the object ID or display name, or a signal
// query such as `is_scammer > 90 and trust_score < 1` (see [Search and
// conditions](https://sigwise.ai/docs/guides/queries)).
//
// GET /v1/objects
func (s *ObjectsService) List(ctx context.Context, params *ListObjectsParams) (*ObjectList, error) {
	var out ObjectList
	if err := s.c.do(ctx, "GET", "/v1/objects", nil, params.values(), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get — get an object's analysis.
//
// Returns the latest answer for each signal computed for the object, plus the
// configured signals that have no answer yet (`pending`).
//
// Reads are cached for a few seconds; the `X-Cache` header says whether this
// one was a `HIT` or a `MISS`. Ingesting events and completed analyses
// invalidate the cache.
//
// GET /v1/objects/{object_id}
func (s *ObjectsService) Get(ctx context.Context, objectID string) (*ObjectAnalysis, error) {
	var out ObjectAnalysis
	if err := s.c.do(ctx, "GET", "/v1/objects/{object_id}", map[string]string{"object_id": objectID}, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetState — get an object's compacted history.
//
// Older events are folded into a rolling summary so the analyzer gets a
// bounded payload while keeping long-term signal. This returns that summary
// and the compaction cursor.
//
// GET /v1/objects/{object_id}/state
func (s *ObjectsService) GetState(ctx context.Context, objectID string) (*ObjectState, error) {
	var out ObjectState
	if err := s.c.do(ctx, "GET", "/v1/objects/{object_id}/state", map[string]string{"object_id": objectID}, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Analyze — re-analyze an object.
//
// Schedules an immediate re-analysis without a new event, for example right
// after adding a signal. Runs at live priority; poll `GET
// /v1/objects/{object_id}` for the result. Returns `404` when the object has
// no events.
//
// POST /v1/objects/{object_id}/analyze
func (s *ObjectsService) Analyze(ctx context.Context, objectID string) (*AnalyzeScheduled, error) {
	var out AnalyzeScheduled
	if err := s.c.do(ctx, "POST", "/v1/objects/{object_id}/analyze", map[string]string{"object_id": objectID}, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// EventsService groups the events operations. Events and messages are the
// evidence an object's answers are computed from.
type EventsService struct{ c *Client }

// Ingest — ingest events.
//
// Records one or more events or messages about an object.
//
// **Asynchronous (default).** Returns `202` immediately and schedules a
// debounced analysis: a burst of events for one object coalesces into a single
// analysis once activity settles. Read the answers with `GET
// /v1/objects/{object_id}` or receive them by webhook.
//
// **Synchronous (`wait: true`).** Blocks on the analyzer and returns the
// verdict inline with `200`, so you can approve, review or block content
// before publishing it. Restrict scoring to some signals with `signals`, and
// score the request's events in isolation with `include_history: false`.
//
// Returns `402` when the tenant's balance is empty. A synchronous request
// returns `429` when the account already has the maximum number of synchronous
// analyses in flight (8 by default), and `503` with `analyzer_busy` when the
// analyzer is throttling; the events are recorded either way, so don't resend
// them: after `Retry-After`, request an analysis with `POST
// /v1/objects/{object_id}/analyze` and read the answers with `GET
// /v1/objects/{object_id}` or by webhook.
//
// **Safe retries.** Send an `Idempotency-Key` header (any unique string, such
// as a UUID) and retry with the same key after a timeout or a `5xx`: the
// events are recorded once. A repeat of an asynchronous request is answered
// like the first and carries `Idempotent-Replayed: true`. A repeat of a
// synchronous request returns `409` without analyzing (or charging) again;
// read the verdict with `GET /v1/objects/{object_id}`. Reusing a key for a
// different object returns `422`. Keys are remembered for 24 hours.
//
// POST /v1/objects/{object_id}/events
func (s *EventsService) Ingest(ctx context.Context, objectID string, body *IngestRequest) (*IngestEventsResponse, error) {
	var payload any
	if body != nil {
		payload = body
	}
	status, raw, err := s.c.doRaw(ctx, "POST", "/v1/objects/{object_id}/events", map[string]string{"object_id": objectID}, nil, payload)
	if err != nil {
		return nil, err
	}
	out := &IngestEventsResponse{StatusCode: status}
	var target any
	switch status {
	case 200:
		out.ModerationVerdict = new(ModerationVerdict)
		target = out.ModerationVerdict
	case 202:
		out.IngestAccepted = new(IngestAccepted)
		target = out.IngestAccepted
	default:
		return out, nil
	}
	if err := decodeJSON(raw, target); err != nil {
		return nil, fmt.Errorf("sigwise: decode POST /v1/objects/{object_id}/events response: %w", err)
	}
	return out, nil
}

// List — list an object's events.
//
// Returns up to the 200 most recent events and messages recorded for the
// object, newest first.
//
// GET /v1/objects/{object_id}/events
func (s *EventsService) List(ctx context.Context, objectID string) (*EventList, error) {
	var out EventList
	if err := s.c.do(ctx, "GET", "/v1/objects/{object_id}/events", map[string]string{"object_id": objectID}, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// SignalsService groups the signals operations. A signal is a question you ask
// about every object, such as "is this a scammer?" (`noul`), "how trustworthy
// is this user?" (`score`) or "what is their buyer intent?" (`choice`).
type SignalsService struct{ c *Client }

// List — list signals.
//
// GET /v1/signals
func (s *SignalsService) List(ctx context.Context) (*SignalList, error) {
	var out SignalList
	if err := s.c.do(ctx, "GET", "/v1/signals", nil, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Upsert — create or update a signal.
//
// Creates the signal, or replaces its definition. `instructions` and
// `criteria` are passed to the analyzer verbatim; the shape of `criteria`
// depends on `type`:
//
// | `type` | `criteria` |
// |----------|------------------------------------------------------|
// | `noul` | object with optional `true` / `false` descriptions |
// | `score` | ordered array of level descriptions, low to high |
// | `choice` | object mapping each option to a description or null |
//
// Creating a signal does not analyze existing objects unless the tenant
// setting `auto_backfill_signals` is on; start a backfill explicitly with
// `POST /v1/signals/{key}/backfill`.
//
// PUT /v1/signals/{key}
func (s *SignalsService) Upsert(ctx context.Context, key string, body *SignalInput) (*Signal, error) {
	var payload any
	if body != nil {
		payload = body
	}
	var out Signal
	if err := s.c.do(ctx, "PUT", "/v1/signals/{key}", map[string]string{"key": key}, nil, payload, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete — delete a signal.
//
// DELETE /v1/signals/{key}
func (s *SignalsService) Delete(ctx context.Context, key string) error {
	return s.c.do(ctx, "DELETE", "/v1/signals/{key}", map[string]string{"key": key}, nil, nil, nil)
}

// GetBackfill — get backfill estimate and progress.
//
// Returns how many existing objects have no answer for the signal and what
// analyzing them would cost now, plus the progress of the most recent backfill
// (`null` if none was started).
//
// GET /v1/signals/{key}/backfill
func (s *SignalsService) GetBackfill(ctx context.Context, key string) (*BackfillStatus, error) {
	var out BackfillStatus
	if err := s.c.do(ctx, "GET", "/v1/signals/{key}/backfill", map[string]string{"key": key}, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// StartBackfill — start a backfill.
//
// Re-analyzes, for this signal only, every existing object that has no answer
// for it. Jobs run at bulk priority so they never delay live ingest. Each
// analysis is billed. Returns `409` if the signal is disabled.
//
// POST /v1/signals/{key}/backfill
func (s *SignalsService) StartBackfill(ctx context.Context, key string) (*SignalBackfill, error) {
	var out SignalBackfill
	if err := s.c.do(ctx, "POST", "/v1/signals/{key}/backfill", map[string]string{"key": key}, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// SettingsService groups the settings operations. The authenticated principal
// and tenant settings.
type SettingsService struct{ c *Client }

// Get — get tenant settings.
//
// GET /v1/settings
func (s *SettingsService) Get(ctx context.Context) (*Settings, error) {
	var out Settings
	if err := s.c.do(ctx, "GET", "/v1/settings", nil, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update — update tenant settings.
//
// Omitted fields are left unchanged.
//
// PATCH /v1/settings
func (s *SettingsService) Update(ctx context.Context, body *SettingsUpdate) (*Settings, error) {
	var payload any
	if body != nil {
		payload = body
	}
	var out Settings
	if err := s.c.do(ctx, "PATCH", "/v1/settings", nil, nil, payload, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// WebhooksService groups the webhooks operations. Webhook endpoints receive a
// signed `POST` for the event types they subscribe to: `analysis.completed`
// each time an analysis completes, and `rule.triggered` when a rule with a
// webhook action fires.
type WebhooksService struct{ c *Client }

// List — list webhook endpoints.
//
// GET /v1/webhooks
func (s *WebhooksService) List(ctx context.Context) (*WebhookEndpointList, error) {
	var out WebhookEndpointList
	if err := s.c.do(ctx, "GET", "/v1/webhooks", nil, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create — register a webhook endpoint.
//
// Registers an endpoint and returns its signing secret. **The secret is shown
// only once**; store it to verify deliveries.
//
// POST /v1/webhooks
func (s *WebhooksService) Create(ctx context.Context, body *WebhookEndpointCreate) (*WebhookEndpointCreated, error) {
	var payload any
	if body != nil {
		payload = body
	}
	var out WebhookEndpointCreated
	if err := s.c.do(ctx, "POST", "/v1/webhooks", nil, nil, payload, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get — get a webhook endpoint.
//
// GET /v1/webhooks/{endpoint_id}
func (s *WebhooksService) Get(ctx context.Context, endpointID string) (*WebhookEndpoint, error) {
	var out WebhookEndpoint
	if err := s.c.do(ctx, "GET", "/v1/webhooks/{endpoint_id}", map[string]string{"endpoint_id": endpointID}, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update — update a webhook endpoint.
//
// Omitted fields are left unchanged.
//
// PATCH /v1/webhooks/{endpoint_id}
func (s *WebhooksService) Update(ctx context.Context, endpointID string, body *WebhookEndpointUpdate) (*WebhookEndpoint, error) {
	var payload any
	if body != nil {
		payload = body
	}
	var out WebhookEndpoint
	if err := s.c.do(ctx, "PATCH", "/v1/webhooks/{endpoint_id}", map[string]string{"endpoint_id": endpointID}, nil, payload, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete — delete a webhook endpoint.
//
// Removes the endpoint and its deliveries.
//
// DELETE /v1/webhooks/{endpoint_id}
func (s *WebhooksService) Delete(ctx context.Context, endpointID string) error {
	return s.c.do(ctx, "DELETE", "/v1/webhooks/{endpoint_id}", map[string]string{"endpoint_id": endpointID}, nil, nil, nil)
}

// WebhookDeliveriesService groups the webhookDeliveries operations. Webhook
// endpoints receive a signed `POST` for the event types they subscribe to:
// `analysis.completed` each time an analysis completes, and `rule.triggered`
// when a rule with a webhook action fires.
type WebhookDeliveriesService struct{ c *Client }

// List — list webhook deliveries.
//
// Recent deliveries, newest first. Filter with `status=dead` to inspect the
// dead-letter queue.
//
// GET /v1/webhook_deliveries
func (s *WebhookDeliveriesService) List(ctx context.Context, params *ListWebhookDeliveriesParams) (*WebhookDeliveryList, error) {
	var out WebhookDeliveryList
	if err := s.c.do(ctx, "GET", "/v1/webhook_deliveries", nil, params.values(), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Replay — replay a delivery.
//
// Re-queues a delivery (for example one in the dead-letter queue) for another
// attempt.
//
// POST /v1/webhook_deliveries/{delivery_id}/replay
func (s *WebhookDeliveriesService) Replay(ctx context.Context, deliveryID string) (*WebhookDelivery, error) {
	var out WebhookDelivery
	if err := s.c.do(ctx, "POST", "/v1/webhook_deliveries/{delivery_id}/replay", map[string]string{"delivery_id": deliveryID}, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// RulesService groups the rules operations. A rule fires an action (email,
// Slack or webhook) when an object's signal values cross a line you care
// about, such as `is_scammer >= 90`.
type RulesService struct{ c *Client }

// List — list rules.
//
// GET /v1/rules
func (s *RulesService) List(ctx context.Context) (*RuleList, error) {
	var out RuleList
	if err := s.c.do(ctx, "GET", "/v1/rules", nil, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create — create a rule.
//
// The condition is validated against the tenant's signals, and a `webhook`
// action must reference a registered endpoint subscribed to `rule.triggered`.
//
// POST /v1/rules
func (s *RulesService) Create(ctx context.Context, body *RuleCreate) (*Rule, error) {
	var payload any
	if body != nil {
		payload = body
	}
	var out Rule
	if err := s.c.do(ctx, "POST", "/v1/rules", nil, nil, payload, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get — get a rule.
//
// GET /v1/rules/{rule_id}
func (s *RulesService) Get(ctx context.Context, ruleID string) (*Rule, error) {
	var out Rule
	if err := s.c.do(ctx, "GET", "/v1/rules/{rule_id}", map[string]string{"rule_id": ruleID}, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update — update a rule.
//
// Omitted fields are left unchanged. The resulting condition and action are
// re-validated.
//
// PATCH /v1/rules/{rule_id}
func (s *RulesService) Update(ctx context.Context, ruleID string, body *RuleUpdate) (*Rule, error) {
	var payload any
	if body != nil {
		payload = body
	}
	var out Rule
	if err := s.c.do(ctx, "PATCH", "/v1/rules/{rule_id}", map[string]string{"rule_id": ruleID}, nil, payload, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete — delete a rule.
//
// DELETE /v1/rules/{rule_id}
func (s *RulesService) Delete(ctx context.Context, ruleID string) error {
	return s.c.do(ctx, "DELETE", "/v1/rules/{rule_id}", map[string]string{"rule_id": ruleID}, nil, nil, nil)
}

// RuleFiringsService groups the ruleFirings operations. A rule fires an action
// (email, Slack or webhook) when an object's signal values cross a line you
// care about, such as `is_scammer >= 90`.
type RuleFiringsService struct{ c *Client }

// List — list rule firings.
//
// The audit log of rule firings and their action outcomes, newest first.
//
// GET /v1/rule_firings
func (s *RuleFiringsService) List(ctx context.Context, params *ListRuleFiringsParams) (*RuleFiringList, error) {
	var out RuleFiringList
	if err := s.c.do(ctx, "GET", "/v1/rule_firings", nil, params.values(), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// APIKeysService groups the apiKeys operations. Create, rotate and revoke the
// keys your integrations sign requests with.
type APIKeysService struct{ c *Client }

// List — list API keys.
//
// Revoked keys are not listed. Secrets are never returned.
//
// GET /v1/api_keys
func (s *APIKeysService) List(ctx context.Context) (*APIKeyList, error) {
	var out APIKeyList
	if err := s.c.do(ctx, "GET", "/v1/api_keys", nil, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create — create an API key.
//
// Mints a key ID and signing secret. **The secret is shown only once.**
//
// POST /v1/api_keys
func (s *APIKeysService) Create(ctx context.Context, body *APIKeyCreate) (*APIKeySecret, error) {
	var payload any
	if body != nil {
		payload = body
	}
	var out APIKeySecret
	if err := s.c.do(ctx, "POST", "/v1/api_keys", nil, nil, payload, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update — update an API key.
//
// Rename a key, or deactivate and reactivate it. Use `DELETE` to revoke.
//
// PATCH /v1/api_keys/{key_id}
func (s *APIKeysService) Update(ctx context.Context, keyID string, body *APIKeyUpdate) (*APIKey, error) {
	var payload any
	if body != nil {
		payload = body
	}
	var out APIKey
	if err := s.c.do(ctx, "PATCH", "/v1/api_keys/{key_id}", map[string]string{"key_id": keyID}, nil, payload, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Revoke — revoke an API key.
//
// The key stops authenticating immediately. Its ID is never reissued.
//
// DELETE /v1/api_keys/{key_id}
func (s *APIKeysService) Revoke(ctx context.Context, keyID string) error {
	return s.c.do(ctx, "DELETE", "/v1/api_keys/{key_id}", map[string]string{"key_id": keyID}, nil, nil, nil)
}

// Rotate — rotate an API key's secret.
//
// Keeps the key ID and replaces the secret. The old secret stops working
// immediately; the new one is returned only once.
//
// POST /v1/api_keys/{key_id}/rotate
func (s *APIKeysService) Rotate(ctx context.Context, keyID string) (*APIKeySecret, error) {
	var out APIKeySecret
	if err := s.c.do(ctx, "POST", "/v1/api_keys/{key_id}/rotate", map[string]string{"key_id": keyID}, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// BillingService groups the billing operations. Prepaid balance, the billing
// ledger, and card top-ups.
type BillingService struct{ c *Client }

// GetBalance — get the prepaid balance.
//
// GET /v1/billing
func (s *BillingService) GetBalance(ctx context.Context) (*Balance, error) {
	var out Balance
	if err := s.c.do(ctx, "GET", "/v1/billing", nil, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListLedger — list ledger entries.
//
// One page of the billing ledger, newest first. Pass the previous page's
// `next_cursor` as `cursor` to continue; it is empty on the last page.
//
// GET /v1/billing/ledger
func (s *BillingService) ListLedger(ctx context.Context, params *ListLedgerParams) (*LedgerPage, error) {
	var out LedgerPage
	if err := s.c.do(ctx, "GET", "/v1/billing/ledger", nil, params.values(), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateCheckout — start a card top-up.
//
// Creates a hosted Stripe Checkout Session for the amount and returns its URL.
// The balance is credited only once Stripe confirms the payment. Returns `503`
// when card payments are not configured.
//
// POST /v1/billing/checkout
func (s *BillingService) CreateCheckout(ctx context.Context, body *CheckoutCreate) (*CheckoutSession, error) {
	var payload any
	if body != nil {
		payload = body
	}
	var out CheckoutSession
	if err := s.c.do(ctx, "POST", "/v1/billing/checkout", nil, nil, payload, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCheckout — get a top-up's status.
//
// Whether the Checkout Session's payment has been credited to the balance yet.
//
// GET /v1/billing/checkout/{session_id}
func (s *BillingService) GetCheckout(ctx context.Context, sessionID string) (*CheckoutStatus, error) {
	var out CheckoutStatus
	if err := s.c.do(ctx, "GET", "/v1/billing/checkout/{session_id}", map[string]string{"session_id": sessionID}, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UsageService groups the usage operations. Analysis volume, spend and token
// usage over a date range.
type UsageService struct{ c *Client }

// Get — get usage.
//
// Analyses, spend and tokens over an inclusive UTC date range (at most 366
// days), with a zero-filled daily series and breakdowns by model, source
// (`async` / `sync`) and signal. Defaults to the last 30 days.
//
// GET /v1/usage
func (s *UsageService) Get(ctx context.Context, params *GetUsageParams) (*Usage, error) {
	var out Usage
	if err := s.c.do(ctx, "GET", "/v1/usage", nil, params.values(), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func decodeJSON(raw []byte, v any) error {
	if len(raw) == 0 {
		return nil
	}
	return json.Unmarshal(raw, v)
}
