// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

package sigwise

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"strconv"
	"time"
)

// ErrWebhookSignature is returned for a webhook delivery whose signature,
// timestamp or payload is not valid.
var ErrWebhookSignature = errors.New("sigwise: invalid webhook signature")

// DefaultWebhookTolerance is how old a delivery's timestamp may be.
const DefaultWebhookTolerance = 5 * time.Minute

// VerifyWebhookSignature checks a webhook delivery: signature (the
// X-Webhook-Signature header) must be the HMAC-SHA256 of
// "<timestamp>.<payload>" keyed with the endpoint secret, and timestamp (the
// X-Webhook-Timestamp header) must be within tolerance of now. Pass the raw
// body, exactly as received. A tolerance of 0 uses DefaultWebhookTolerance.
func VerifyWebhookSignature(payload []byte, signature, timestamp, secret string, tolerance time.Duration) error {
	if signature == "" || timestamp == "" {
		return ErrWebhookSignature
	}
	ts, err := strconv.ParseInt(timestamp, 10, 64)
	if err != nil {
		return ErrWebhookSignature
	}
	if tolerance == 0 {
		tolerance = DefaultWebhookTolerance
	}
	if age := time.Since(time.Unix(ts, 0)); age > tolerance || age < -tolerance {
		return ErrWebhookSignature
	}
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write([]byte(timestamp + "."))
	mac.Write(payload)
	want := "sha256=" + hex.EncodeToString(mac.Sum(nil))
	if !hmac.Equal([]byte(want), []byte(signature)) {
		return ErrWebhookSignature
	}
	return nil
}

// WebhookEvent is a verified webhook delivery. Event names its type, and the
// matching field holds the parsed body.
type WebhookEvent struct {
	Event                  string
	AnalysisCompletedEvent *AnalysisCompletedEvent
	RuleTriggeredEvent     *RuleTriggeredEvent
	// Raw is the delivery body.
	Raw json.RawMessage
}

// ParseWebhookEvent verifies a webhook delivery (see VerifyWebhookSignature)
// and parses its body.
func ParseWebhookEvent(payload []byte, signature, timestamp, secret string, tolerance time.Duration) (*WebhookEvent, error) {
	if err := VerifyWebhookSignature(payload, signature, timestamp, secret, tolerance); err != nil {
		return nil, err
	}
	var head struct {
		Event string `json:"event"`
	}
	if err := json.Unmarshal(payload, &head); err != nil {
		return nil, err
	}
	ev := &WebhookEvent{Event: head.Event, Raw: append(json.RawMessage(nil), payload...)}
	var err error
	switch head.Event {
	case "analysis.completed":
		ev.AnalysisCompletedEvent = new(AnalysisCompletedEvent)
		err = json.Unmarshal(payload, ev.AnalysisCompletedEvent)
	case "rule.triggered":
		ev.RuleTriggeredEvent = new(RuleTriggeredEvent)
		err = json.Unmarshal(payload, ev.RuleTriggeredEvent)
	}
	if err != nil {
		return nil, err
	}
	return ev, nil
}
